export const sampleData = [
  { id: 1, name: "John", country: "USA", age: 37 },
  { id: 2, name: "Alice", country: "India", age: 32 },
  { id: 3, name: "Bob", country: "Korea", age: 25 },
  { id: 4, name: "Doe", country: "Japan", age: 20 },
  { id: 5, name: "Jane", country: "China", age: 30 },
  { id: 6, name: "Smith", country: "Brazil", age: 45 },
  { id: 7, name: "Tom", country: "Canada", age: 40 },
  { id: 8, name: "Jerry", country: "Australia", age: 35 },
  { id: 9, name: "Marry", country: "Germany", age: 28 },
  { id: 10, name: "Harry", country: "France", age: 22 },
  { id: 11, name: "Sara", country: "Italy", age: 27 },
  { id: 12, name: "Paul", country: "Spain", age: 33 },
  { id: 13, name: "Jessica", country: "Mexico", age: 38 },
  { id: 14, name: "Michael", country: "Russia", age: 42 },
  { id: 15, name: "Emma", country: "South Africa", age: 29 },
  { id: 16, name: "Oliver", country: "USA", age: 31 },
  { id: 17, name: "Ava", country: "India", age: 26 },
  { id: 18, name: "William", country: "Korea", age: 34 },
  { id: 19, name: "Sophia", country: "Japan", age: 23 },
  { id: 20, name: "James", country: "China", age: 36 },
  { id: 21, name: "Isabella", country: "Brazil", age: 24 },
  { id: 22, name: "Benjamin", country: "Canada", age: 39 },
  { id: 23, name: "Mia", country: "Australia", age: 21 },
  { id: 24, name: "Lucas", country: "Germany", age: 27 },
  { id: 25, name: "Charlotte", country: "France", age: 32 },
  { id: 26, name: "Henry", country: "Italy", age: 28 },
  { id: 27, name: "Amelia", country: "Spain", age: 30 },
  { id: 28, name: "Alexander", country: "Mexico", age: 33 },
  { id: 29, name: "Harper", country: "Russia", age: 25 },
  { id: 30, name: "Sebastian", country: "South Africa", age: 37 },
  { id: 31, name: "Evelyn", country: "USA", age: 22 },
  { id: 32, name: "Jack", country: "India", age: 35 },
  { id: 33, name: "Abigail", country: "Korea", age: 29 },
  { id: 34, name: "Owen", country: "Japan", age: 31 },
  { id: 35, name: "Ella", country: "China", age: 26 },
  { id: 36, name: "Theodore", country: "Brazil", age: 34 },
  { id: 37, name: "Lily", country: "Canada", age: 23 },
  { id: 38, name: "Jackson", country: "Australia", age: 36 },
  { id: 39, name: "Avery", country: "Germany", age: 24 },
  { id: 40, name: "Levi", country: "France", age: 39 },
  { id: 41, name: "Sofia", country: "Italy", age: 21 },
  { id: 42, name: "David", country: "Spain", age: 27 },
  { id: 43, name: "Aria", country: "Mexico", age: 32 },
  { id: 44, name: "Matthew", country: "Russia", age: 28 },
  { id: 45, name: "Scarlett", country: "South Africa", age: 30 },
  { id: 46, name: "Joseph", country: "USA", age: 33 },
  { id: 47, name: "Grace", country: "India", age: 25 },
  { id: 48, name: "Samuel", country: "Korea", age: 37 },
  { id: 49, name: "Chloe", country: "Japan", age: 22 },
  { id: 50, name: "Daniel", country: "China", age: 35 },
  { id: 51, name: "Liam", country: "Brazil", age: 29 },
  { id: 52, name: "Noah", country: "Canada", age: 31 },
  { id: 53, name: "Elijah", country: "Australia", age: 27 },
  { id: 54, name: "Logan", country: "Germany", age: 34 },
  { id: 55, name: "Mason", country: "France", age: 28 },
  { id: 56, name: "Lucas", country: "Italy", age: 32 },
  { id: 57, name: "Ethan", country: "Spain", age: 30 },
  { id: 58, name: "Aiden", country: "Mexico", age: 26 },
  { id: 59, name: "James", country: "Russia", age: 33 },
  { id: 60, name: "Carter", country: "South Africa", age: 35 },
];
